#
# NanoLimbo configuration
#

# Server's host address and port. Set ip empty to use public address
bind:
  ip: 'localhost'
  port: 65535

# Max number of players can join to server
# Set -1 to make it infinite
maxPlayers: 100

# Server's data in servers list
ping:
  description: '{"text": "&9NanoLimbo"}'
  version: 'NanoLimbo'

# Available dimensions: OVERWORLD, NETHER, THE_END
dimension: THE_END

# Supports .litematic and .schem
# Leave empty for void
schematic:

# Setup player's game mode
# 0 - Survival
# 1 - Creative (hide HP and food bar)
# 2 - Adventure
# 3 - Spectator (hide all UI bars)
# Spectator works on 1.8+ clients
gameMode: 3

# Player spawn position. x,y,z are doubles, yaw,pitch are floats
spawnPos:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0

# Player info forwarding support.
# Available types:
#  - NONE
#  - LEGACY
#  - MODERN
#  - BUNGEE_GUARD
# Don't use secret if you do not use MODERN type
infoForwarding:
  type: NONE
  secret: '<YOUR_SECRET_HERE>'
  tokens:
    - '<BUNGEE_GUARD_TOKEN>'

# Read timeout for connections in milliseconds
readTimeout: 30000

# Define log level. For production, I'd recommend to use level 2
# Log levels:
# 0 - Display only errors
# 1 - Display errors, warnings
# 2 - Display errors, warnings, info
# 3 - Display errors, warnings, info, debug
debugLevel: 2

# Warning! Do not touch params of this block if you are not completely sure what is this!
netty:
  # Use a Linux native transport type, if it possible
  useEpoll: true
  # EventLoopGroup threads count
  threads:
    bossGroup: 1
    workerGroup: 4
